# Generated by Django 5.0.1 on 2025-03-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='delivery_address',
            field=models.CharField(choices=[('tashkent-samarkand', 'Tashkent-Samarkand'), ('samarkand-tashkent', 'Samarkand-Tashkent')], max_length=50),
        ),
    ]
