# Generated by Django 5.0.1 on 2025-03-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('uz', 'Uzbek'), ('kr', 'Krill')], default='uz', max_length=2),
        ),
    ]
